version: '3.8'
services:

  nestjs:
    build: ./containers/nestjs
    image: nestjs
    container_name: nestjs
    env_file: .env
    init: true  # Ensures quick shutdown by sending SIGTERM to child processes
    restart: on-failure
    ports:
      - "4242:4242"
    volumes:
      - ./containers/nestjs/src/:/nestjs/src/
    depends_on:
      - react 
      - db     # Ensures that the database service is started before this service

  react:
    build: ./containers/react
    image: react
    container_name: react
    env_file: .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    init: true
    restart: on-failure
    ports:
      - "2424:2424"
    volumes:
      - ./containers/react/src/:/usr/src/app/src/

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/
    ports:
      - "8080:80"
    environment:
      - ./nginx/.env
    links:
      - react
      - nestjs

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=newadmin@example.com
      - PGADMIN_DEFAULT_PASSWORD=newpassword
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  db_volume:
