version: '3.8'
services:
  nestjs:
    build: ./containers/nestjs
    image: nestjs
    container_name: nestjs
    env_file: .env
    init: true  # Ensures quick shutdown by sending SIGTERM to child processes
    restart: on-failure
    environment:
      - PORT=${PORT}
    ports:
      - "4242:4242"
    volumes:
      - ./containers/nestjs/:/nestjs/code/
    depends_on:
      #- svelte  # Ensures that Svelte service is started before this service
      - db     # Ensures that the database service is started before this service

  # svelte:
  #   build: ./containers/svelte
  #   image: svelte
  #   container_name: svelte
  #   env_file: .env
  #   init: true
  #   restart: on-failure
  #   ports:
  #     - "2424:2424"
  #   volumes:
  #     - ./containers/svelte/:/svelte/code/

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  db_volume:
