version: '3.8'
services:

  nestjs:
    build: 
      context: . 
      dockerfile: ./apps/nestjs/Dockerfile
    container_name: nestjs
    env_file: .env
    init: true  # Ensures quick shutdown by sending SIGTERM to child processes
    restart: on-failure
    ports:
      - "4242:4242"
    volumes:
      - shared_src:/nestjs
    depends_on:
      - react 
      - db     # Ensures that the database service is started before this service

  react:
    build:
      context: . 
      dockerfile: ./apps/react/Dockerfile
    container_name: react
    env_file: .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    init: true
    restart: on-failure
    ports:
      - "2424:2424"
    volumes:
      - shared_src:/usr/src/app

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "4433:80"
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nestjs
      - react
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=newadmin@example.com
      - PGADMIN_DEFAULT_PASSWORD=newpassword
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  shared_src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .
  db_volume:
